CREATE DATABASE Weather;
USE Weather;
CREATE TABLE WindFarm(
	TIMESTAMP DATETIME COMMENT 'Time is CST, UTC-6. Does not adhere to Daylight Savings',
	RECORD INTEGER COMMENT 'Flat-file Record Number',
	Batt_Volt_Min DOUBLE COMMENT 'Battery Min (Volts)',
	PTemp_C DOUBLE COMMENT '(Degrees C)',
	WS_C1_60m_Prim_Avg DOUBLE COMMENT 'Primary Sensor, Average Wind Speed (m/s) at 60m',
	WS_C1_60m_Prim_Max DOUBLE COMMENT 'Primary Sensor, Maximum Wind Speed (m/s) at 60m',
	WS_C1_60m_Prim_Min DOUBLE COMMENT 'Primary Sensor, Minimum Wind Speed (m/s) at 60m',
	WS_C1_60m_Prim_Std DOUBLE COMMENT 'Primary Sensor, Standard Deviation of Wind Speed (m/s) at 60m',
	WS_C1_60m_Redun_Avg DOUBLE COMMENT 'Redundant Sensor, Average Wind Speed (m/s) at 60m',
	WS_C1_60m_Redun_Max DOUBLE COMMENT 'Redundant Sensor, Maximum Wind Speed (m/s) at 60m',
	WS_C1_60m_Redun_Min DOUBLE COMMENT 'Redundant Sensor, Minimum Wind Speed (m/s) at 60m',
	WS_C1_60m_Redun_Std DOUBLE COMMENT 'Redundant Sensor, Standard Deviation of Wind Speed (m/s) at 60m',
	WS_C1_50m_Prim_Avg DOUBLE COMMENT 'Primary Sensor, Average Wind Speed (m/s) at 50m',
	WS_C1_50m_Prim_Max DOUBLE COMMENT 'Primary Sensor, Maximum Wind Speed (m/s) at 50m',
	WS_C1_50m_Prim_Min DOUBLE COMMENT 'Primary Sensor, Minimum Wind Speed (m/s) at 50m',
	WS_C1_50m_Prim_Std DOUBLE COMMENT 'Primary Sensor, Standard Deviation of Wind Speed (m/s) at 50m',
	WS_C1_40m_Prim_Avg DOUBLE COMMENT 'Primary Sensor, Average Wind Speed (m/s) at 40m',
	WS_C1_40m_Prim_Max DOUBLE COMMENT 'Primary Sensor, Maximum Wind Speed (m/s) at 40m',
	WS_C1_40m_Prim_Min DOUBLE COMMENT 'Primary Sensor, Minimum Wind Speed (m/s) at 40m',
	WS_C1_40m_Prim_Std DOUBLE COMMENT 'Primary Sensor, Standard Deviation of Wind Speed (m/s) at 40m',
	WS_C1_40m_Redun_Avg DOUBLE COMMENT 'Redundant Sensor, Average Wind Speed (m/s) at 40m',
	WS_C1_40m_Redun_Max DOUBLE COMMENT 'Redundant Sensor, Maximum Wind Speed (m/s) at 40m',
	WS_C1_40m_Redun_Min DOUBLE COMMENT 'Redundant Sensor, Minimum Wind Speed (m/s) at 40m',
	WS_C1_40m_Redun_Std DOUBLE COMMENT 'Redundant Sensor, Standard Deviation of Wind Speed (m/s) at 40m',
	WS_C1_10m_Prim_Avg DOUBLE COMMENT 'Primary Sensor, Average Wind Speed (m/s) at 10m',
	WS_C1_10m_Prim_Max DOUBLE COMMENT 'Primary Sensor, Maximum Wind Speed (m/s) at 10m',
	WS_C1_10m_Prim_Min DOUBLE COMMENT 'Primary Sensor, Minimum Wind Speed (m/s) at 10m',
	WS_C1_10m_Prim_Std DOUBLE COMMENT 'Primary Sensor, Standard Deviation of Wind Speed (m/s) at 10m',
	WD_200P_59m_WVT DOUBLE COMMENT 'Wind Direction (m/s)',
	WD_200P_59m_SD DOUBLE COMMENT 'Wind Direction (Degrees)',
	WD_200P_49m_WVT DOUBLE COMMENT 'Wind Direction (m/s)',
	WD_200P_49m_SD DOUBLE COMMENT 'Wind Direction (Degrees)',
	Tmp_110S_5ft_Avg DOUBLE COMMENT 'Average Temperature (Degrees C) at 5 ft',
	Tmp_110S_5ft_Max DOUBLE COMMENT 'Maximum Temperature (Degrees C) at 5 ft',
	Tmp_110S_5ft_Min DOUBLE COMMENT 'Minimum Temperature (Degrees C) at 5 ft',
	Tmp_110S_5ft_Std DOUBLE COMMENT 'Standard Deviation of Temperature (Degrees C) at 5 ft',
	Tmp_110S_10ft_Avg DOUBLE COMMENT 'Average Temperature (Degrees C) at 10 ft',
	Tmp_110S_10ft_Max DOUBLE COMMENT 'Maximum Temperature (Degrees C) at 10 ft',
	Tmp_110S_10ft_Min DOUBLE COMMENT 'Minimum Temperature (Degrees C) at 10 ft',
	Tmp_110S_10ft_Std DOUBLE COMMENT 'Standard Deviation of Temperature (Degrees C) at 10 ft',
	RH_RH5_5ft_Avg DOUBLE COMMENT 'Average Relative Humidity (Percent) at 5 ft',
	RH_RH5_5ft_Max DOUBLE COMMENT 'Maximum Relative Humidity (Percent) at 5 ft',
	RH_RH5_5ft_Min DOUBLE COMMENT 'Minimum Relative Humidity (Percent) at 5 ft',
	RH_RH5_5ft_Std DOUBLE COMMENT 'Standard Deviation of Relative Humidity (Percent) at 5 ft',
	RH_RH5_10ft_Avg DOUBLE COMMENT 'Average Relative Humidity (Percent) at 10 ft',
	RH_RH5_10ft_Max DOUBLE COMMENT 'Maximum Relative Humidity (Percent) at 10 ft',
	RH_RH5_10ft_Min DOUBLE COMMENT 'Minimum Relative Humidity (Percent) at 10 ft',
	RH_RH5_10ft_Std DOUBLE COMMENT 'Standard Deviation of Relative Humidity (Percent) at 10 ft',
	BP_BP20_5ft_Avg DOUBLE COMMENT 'Average Barometric Pressure (kPa) at 5 ft',
	BP_BP20_5ft_Max DOUBLE COMMENT 'Maximum Barometric Pressure (kPa) at 5 ft',
	BP_BP20_5ft_Min DOUBLE COMMENT 'Minimum Barometric Pressure (kPa) at 5 ft',
	BP_BP20_5ft_Std DOUBLE COMMENT 'Standard Deviation of Barometric Pressure (kPa) at 5 ft',
	Precip_NVL_5ft_Tot DOUBLE COMMENT 'Total Precipitation (mm)',
	Solar_Rad_LP02_5ft_Avg DOUBLE COMMENT 'Average Solar Radiation (Wm^2)',
	Solar_Rad_LP02_5ft_Max DOUBLE COMMENT 'Maximum Solar Radiation (Wm^2)',
	Solar_Rad_LP02_5ft_Min DOUBLE COMMENT 'Minimum Solar Radiation (Wm^2)',
	Solar_Rad_LP02_5ft_Std DOUBLE COMMENT 'Standard Deviation of Solar Radiation (Wm^2)',
	Solar_Rad_LP02_5ft_Tot DOUBLE COMMENT 'Total Solar Radiation (Wm^2)',
	Solar_Rad_NR2_5ft_Avg DOUBLE COMMENT 'Average Solar Radiation (Wm^2)',
	Solar_Rad_NR2_5ft_Max DOUBLE COMMENT 'Maximum Solar Radiation (Wm^2)',
	Solar_Rad_NR2_5ft_Min DOUBLE COMMENT 'Minimum Solar Radiation (Wm^2)',
	Solar_Rad_NR2_5ft_Std DOUBLE COMMENT 'Standard Deviation of Solar Radiation (Wm^2)',
	Solar_Rad_NR2_5ft_Tot DOUBLE COMMENT 'Total Solar Radiation (Wm^2)',
	PRIMARY KEY(TIMESTAMP)
)
COMMENT 'Data collected from the WindFarm Weather Station.  Min, Max, Std measurments are taken at 10 minute intervals';

GRANT SELECT ON Weather.* TO '';
CREATE USER 'weatherbot'@'localhost' IDENTIFIED BY 'gsciweather';
GRANT SELECT,UPDATE,INSERT ON Weather.* TO 'weatherbot'@'localhost';